package evenements;

public enum GenreEvenement {
	CHOIX_MOTS, COMPLETION_MOT, ECOULEMENT_DU_TEMPS, MORT, NAISSANCE, PROGRESSION_MOT,
	REPRODUCTION, VARIATION_ENERGIE_ASYMPTOTIQUE, SIGNAL_EXPERIMENTAL;
}
